<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Denise B. Ferrari">

<title>GED-16: Análise de Regressão</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="GED16_AULA01_Exemplo_files/libs/clipboard/clipboard.min.js"></script>
<script src="GED16_AULA01_Exemplo_files/libs/quarto-html/quarto.js"></script>
<script src="GED16_AULA01_Exemplo_files/libs/quarto-html/popper.min.js"></script>
<script src="GED16_AULA01_Exemplo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GED16_AULA01_Exemplo_files/libs/quarto-html/anchor.min.js"></script>
<link href="GED16_AULA01_Exemplo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GED16_AULA01_Exemplo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GED16_AULA01_Exemplo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GED16_AULA01_Exemplo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GED16_AULA01_Exemplo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">GED-16: Análise de Regressão</h1>
<p class="subtitle lead">AULA01: Exemplo (1o. semestre/2023)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Denise B. Ferrari </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">8 de março de 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introdução" class="level2">
<h2 class="anchored" data-anchor-id="introdução">Introdução</h2>
<p>Exemplo “Consumo de Combustível de Automóveis”, retirado do <a href="https://archive.ics.uci.edu/ml/datasets/auto+mpg">UCI Machine Learning Repository</a>.</p>
<p>O objetivo inicial desse estudo era prever o consumo de combustível de automóveis em ambiente urbano (expresso em milhas por galão, mpg), a partir de algumas características do veículo.</p>
<p>Há um total de 398 observações registradas para 9 variáveis de interesse,<br>
incluindo a resposta <code>mpg</code>:</p>
<p><strong>Variáveis</strong></p>
<p><code>mpg</code>: numérica (contínua)<br>
<code>cylinder</code>: categórica (ordinal)<br>
<code>displacement</code>: numérica (contínua)<br>
<code>hp</code>: numérica (contínua)<br>
<code>weight</code>: numérica (contínua)<br>
<code>acceleration</code>: numérica (contínua)<br>
<code>modelyear</code>: numérica (discreta)<br>
<code>origin</code>: categórica (nominal)<br>
<code>carname</code>: categórica (nominal)</p>
<section id="parte-1-análise-preliminar-e-preparação-da-massa-de-dados" class="level3">
<h3 class="anchored" data-anchor-id="parte-1-análise-preliminar-e-preparação-da-massa-de-dados">PARTE 1: Análise Preliminar e Preparação da Massa de Dados</h3>
<p>O primeiro passo consiste em limpar a área de trabalho, utilizando o comando <code>rm(list = ls())</code>, para então ler os dados que se encontram no arquivo <code>auto-mpg.data</code>. O arquivo com os dados foi armazenado em uma pasta chamada <code>AutoMPG</code>, que por sua vez, encontra-se em uma pasta chamada <code>data</code>, que é o local onde se encontra a massa de dados. Os dados são lidos e armazenados em um objeto do tipo tabela, chamada <code>auto</code>. Como sabemos, de antemão, que não há cabeçalho no arquivo de entrada, ou seja, as colunas não têm nomes, fazemos <code>header = FALSE</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Limpa area de trabalho</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Carrega os dados em uma tabela</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>auto <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/AutoMPG/auto-mpg.data"</span>, <span class="at">header =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Podemos obter algumas informações do objeto <code>auto</code> utilizando o comando <code>str(auto)</code> (para obter a estrutura, <em>structure</em>, dos dados):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verifica estrutura dos dados</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(auto)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   398 obs. of  9 variables:
 $ V1: num  18 15 18 16 17 15 14 14 14 15 ...
 $ V2: int  8 8 8 8 8 8 8 8 8 8 ...
 $ V3: num  307 350 318 304 302 429 454 440 455 390 ...
 $ V4: chr  "130.0" "165.0" "150.0" "150.0" ...
 $ V5: num  3504 3693 3436 3433 3449 ...
 $ V6: num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
 $ V7: int  70 70 70 70 70 70 70 70 70 70 ...
 $ V8: int  1 1 1 1 1 1 1 1 1 1 ...
 $ V9: chr  "chevrolet chevelle malibu" "buick skylark 320" "plymouth satellite" "amc rebel sst" ...</code></pre>
</div>
</div>
<p>Verificamos que há um total de 398 observações e 9 variáveis. Cada coluna da tabela corresponde a uma variável (atributo) e as diferentes observações estão nas linhas da tabela, e correspondem a toda informação coletada para cada um dos indivíduos avaliados. As variáveis não tem nomes que façam sentido e foram codificadas como variáveis numéricas contínuas, inteiras, ou caracteres. Nota-se que a variável <code>V4</code>, que corresponde à potência, foi codificada como uma variável categórica (neste caso, dada por um conjunto de caracteres), quando ela deveria ser numérica; já a variável <code>V8</code>, que corresponde à origem do veículo, foi codificada como uma variável “númerica discreta” (ou seja, um número inteiro), quando deveria ser categórica. Precisaremos corrigir esses problemas posteriormente.</p>
<p>É útil dar nomes intutivos às variáveis. Para isso, utilizamos o comando <code>colnames</code> aplicado ao objeto <code>auto</code> e atribuímos a ele o vetor contendo os nomes das variáveis desejados. Podemos verificar que os nomes foram atribuídos corretamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Atribui nomes às variáveis (colunas da tabela)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(auto) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"mpg"</span>, <span class="st">"cylinder"</span>, <span class="st">"displacement"</span>, <span class="st">"hp"</span>, <span class="st">"weight"</span>, <span class="st">"acceleration"</span>, <span class="st">"modelyear"</span>, <span class="st">"origin"</span>, <span class="st">"carname"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># verifica nomes das variáveis</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(auto)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "mpg"          "cylinder"     "displacement" "hp"           "weight"      
[6] "acceleration" "modelyear"    "origin"       "carname"     </code></pre>
</div>
</div>
<p>Agora, recodificando as variáveis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Codificação adequada de variáveis quantitativas (numéricas) e categóricas (fatores)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Usand funções nativas do R:</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$mpg          &lt;- as.numeric  (auto$mpg)</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$cylinder     &lt;- as.factor   (auto$cylinder)</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$displacement &lt;- as.numeric  (auto$displacement)</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$hp           &lt;- as.numeric  (auto$hp)</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$weight       &lt;- as.numeric  (auto$weight)</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$acceleration &lt;- as.numeric  (auto$acceleration)</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$modelyear    &lt;- as.numeric  (auto$modelyear)</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$origin       &lt;- as.factor   (auto$origin)</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># auto$carname      &lt;- as.character(auto$carname)</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># alternativamente, usando funções do pacote `tidyverse`:</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>auto <span class="ot">&lt;-</span> auto <span class="sc">%&gt;%</span> </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"mpg"</span>, <span class="st">"displacement"</span>, <span class="st">"hp"</span>, </span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>              <span class="st">"weight"</span>, <span class="st">"acceleration"</span>, <span class="st">"modelyear"</span>), as.numeric) <span class="sc">%&gt;%</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"cylinder"</span>, <span class="st">"origin"</span>), as.factor) <span class="sc">%&gt;%</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="st">"carname"</span>, as.character)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(auto) <span class="co"># nova verificação</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   398 obs. of  9 variables:
 $ mpg         : num  18 15 18 16 17 15 14 14 14 15 ...
 $ cylinder    : Factor w/ 5 levels "3","4","5","6",..: 5 5 5 5 5 5 5 5 5 5 ...
 $ displacement: num  307 350 318 304 302 429 454 440 455 390 ...
 $ hp          : num  130 165 150 150 140 198 220 215 225 190 ...
 $ weight      : num  3504 3693 3436 3433 3449 ...
 $ acceleration: num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
 $ modelyear   : num  70 70 70 70 70 70 70 70 70 70 ...
 $ origin      : Factor w/ 3 levels "1","2","3": 1 1 1 1 1 1 1 1 1 1 ...
 $ carname     : chr  "chevrolet chevelle malibu" "buick skylark 320" "plymouth satellite" "amc rebel sst" ...</code></pre>
</div>
</div>
<p>As variáveis parecem estar corretamente codificadas.</p>
<p><strong>Resumos numéricos unidimensionais</strong></p>
<p>Resumos numéricos unidimensionais podem ser obtidos utilizando a função <code>summary.</code> Para as variáveis categóricas, a função <code>summary</code> retorna o número de observações em cada classe.</p>
<p>Para as variáveis quantitativas, a função <code>summary</code> fornece o chamado resumo de 5-números (mais a média) . Temos valores mínimo, máximo, 1o. e 3o. quartis, mediana e média.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(auto)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      mpg        cylinder  displacement         hp            weight    
 Min.   : 9.00   3:  4    Min.   : 68.0   Min.   : 46.0   Min.   :1613  
 1st Qu.:17.50   4:204    1st Qu.:104.2   1st Qu.: 75.0   1st Qu.:2224  
 Median :23.00   5:  3    Median :148.5   Median : 93.5   Median :2804  
 Mean   :23.51   6: 84    Mean   :193.4   Mean   :104.5   Mean   :2970  
 3rd Qu.:29.00   8:103    3rd Qu.:262.0   3rd Qu.:126.0   3rd Qu.:3608  
 Max.   :46.60            Max.   :455.0   Max.   :230.0   Max.   :5140  
                                          NA's   :6                     
  acceleration     modelyear     origin    carname         
 Min.   : 8.00   Min.   :70.00   1:249   Length:398        
 1st Qu.:13.82   1st Qu.:73.00   2: 70   Class :character  
 Median :15.50   Median :76.00   3: 79   Mode  :character  
 Mean   :15.57   Mean   :76.01                             
 3rd Qu.:17.18   3rd Qu.:79.00                             
 Max.   :24.80   Max.   :82.00                             
                                                           </code></pre>
</div>
</div>
<p>Note que há 6 observações faltantes para a variável <code>hp</code>. Seria necessário decidir como proceder com relação a elas. Neste exemplo, iremos simplesmente remover estes casos. Esta nem sempre é melhor opção pois, dependendo da qualidade da massa de dados, muitas observações podem acabar sendo excluídas. Note também que há um desbalanceamento no número de observações para as diferentes classes de cilindros; por enquanto, também não faremos nada a respeito disso. Para as demais variáveis não parece haver anomalias óbvias.</p>
<p>Removendo as observações em que há dados faltantes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove linhas correspondentes às obs. faltantes da variável `hp`</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>auto <span class="ot">&lt;-</span> auto <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Gera novo resumo</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(auto)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      mpg        cylinder  displacement         hp            weight    
 Min.   : 9.00   3:  4    Min.   : 68.0   Min.   : 46.0   Min.   :1613  
 1st Qu.:17.00   4:199    1st Qu.:105.0   1st Qu.: 75.0   1st Qu.:2225  
 Median :22.75   5:  3    Median :151.0   Median : 93.5   Median :2804  
 Mean   :23.45   6: 83    Mean   :194.4   Mean   :104.5   Mean   :2978  
 3rd Qu.:29.00   8:103    3rd Qu.:275.8   3rd Qu.:126.0   3rd Qu.:3615  
 Max.   :46.60            Max.   :455.0   Max.   :230.0   Max.   :5140  
  acceleration     modelyear     origin    carname         
 Min.   : 8.00   Min.   :70.00   1:245   Length:392        
 1st Qu.:13.78   1st Qu.:73.00   2: 68   Class :character  
 Median :15.50   Median :76.00   3: 79   Mode  :character  
 Mean   :15.54   Mean   :75.98                             
 3rd Qu.:17.02   3rd Qu.:79.00                             
 Max.   :24.80   Max.   :82.00                             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para utilizar os nomes das variaveis diretamente</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(auto) </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Removidas as observações faltantes, restaram 392 observações. Podemos agora gerar alguns resumos gráficos para explorar as relações entre as variáveis.</p>
<p><strong>Resumos gráficos unidimensionais</strong></p>
<p>Informação a respeito da distribuição da variável de resposta é importante para a construção da parte estocástica do modelo de regressão.</p>
<p>Podemos representar a distribuição dos valores observados para uma variável através de um histograma, que pode ser gerado utilizando o código abaixo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma de `mpg`</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto, <span class="fu">aes</span>(<span class="at">x =</span> mpg)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density))) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona linha de densidade estimada (suavização)</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="dv">4</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">fill =</span> <span class="dv">4</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona dispersão unidimensional de `mpg`</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rug</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Embora o histograma seja útil para descrever uma distribuição, sua forma depende da discretização, determinada pelo número de caixas (ou colunas) e da localização de suas fronteiras. Poucas caixas tornam o histograma pouco informativo; por outro lado, com caixas em excesso, o histograma se torna ruidoso, apresentando características irrelevantes.</p>
<p>A curva em azul adicionada ao gráfico é a curva de densidade estimada, que corresponde a uma suavização do histograma e também estima a distribuição da variável de resposta. Diferentemente de um histograma, a curva de densidade estimada é contínua e, em geral, proporciona uma melhor representação da distribuição de uma variável numérica que um histograma.</p>
<p>O comando <code>geom_rug()</code> fornece um diagrama de dispersão unidimensional para a variável, mostrando a localização de cada uma das observações abaixo do histograma.</p>
<p>O boxplot é outra ferramenta gráfica que fornece um resumo da distribuição dos valores da variável sendo analisada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot de `mpg`</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto, <span class="fu">aes</span>(<span class="at">x =</span> mpg, <span class="at">y =</span> <span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona barras de erros</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">stat =</span> <span class="st">"boxplot"</span>, <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona boxplot</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span> () <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona dispersão unidimensional de `mpg`</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rug</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona rótulo aos eixos</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">""</span>, <span class="at">x =</span> <span class="st">"mpg"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>O boxplot nos dá 5 estatísticas robustas e também mostra possíveis <em>outliers</em>. A caixa é delimitada pelos quartis inferior e superior e a linha no centro corresponde à mediana. Portanto, 50% das observações se encontram entre os valores que determinam as extremidades da caixa. O comprimento da caixa é chamado distância ou amplitude inter-quartis (ou IQR) e corresponde à diferença entre os quartis superior e inferior.</p>
<p>As linhas horizontais que se afastam da caixa são os “whiskers”, cujo comprimento é tal que a distância máxima entre as duas extremidades vale 4 * IQR (4 x a amplitude interquartis). Qualquer valor além dos “whiskers” é marcado como um ponto extremo, ou outlier.</p>
<p><strong>Resumos gráficos multidimensionais</strong></p>
<p>Podemos desejar comparar visualmente diferentes distribuições. Por exemplo, podemos querer saber como se comparam os rendimentos de automóveis que possuem motores com diferentes categorias da variável <code>cylinder</code>, ou seja, para diferentes números de cilindros. Pode ser útil construir múltiplos boxplots, histogramas ou curvas de densidade estimada, para diferentes categorias, a fim de comparar as distribuições condicionais de uma certa variável. Podemos sobrepor as distribuições, para tornar a comparação imediata.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplots</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto, <span class="fu">aes</span>(<span class="at">x =</span> mpg, <span class="at">y =</span> cylinder)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogramas </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto, <span class="fu">aes</span>(<span class="at">x =</span> mpg, <span class="at">fill =</span> cylinder)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha =</span> <span class="fl">0.25</span>, <span class="at">position =</span> <span class="st">"identity"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Densidades</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto, <span class="fu">aes</span>(<span class="at">x =</span> mpg, <span class="at">fill =</span> cylinder)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">position =</span> <span class="st">"identity"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>É possível perceber que as distribuições dos rendimentos não parecem todas iguais. Lembre-se de que análise exploratória de dados serve para formular hipóteses, não para chegar a conclusões. Portanto, por enquanto, esta é apenas uma conjectura. A fim de que se possa afirmar se existe ou não diferença estatisticamente significativa no rendimento para motores com diferentes números de cilindros, é necessário aplicar procedimentos formais de testes de hipóteses.</p>
<p>Neste exemplo, temos em um único gráfico representações das distribuições de <code>mpg</code> para automóveis com diferentes números de cilindros. A escolha da melhor ferramenta de visualização depende de cada caso. Aqui, são mais informativos os boxplots e os gráficos de densidade.</p>
<p>Para avaliar a relação entre pares de variáveis quantitativas, é útil utilizar gráficos de dispersão.</p>
<p>Vamos construir uma matriz de gráficos de dispersão para visualizar as relações par-a-par entre as variáveis. Para a visualização, são removidas as variáveis das colunas 8 e 9, correspondentes a <code>origin</code> e <code>carname</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Matriz de gráficos de dispersão (base R)</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(auto[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">8</span>,<span class="dv">9</span>)])</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Matriz de gráficos de dispersão (GGali)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(auto[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">8</span>,<span class="dv">9</span>)])</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Examinar as relações entre os pares de variáveis pode exigir tempo e esforço adicionais, embora os ganhos sejam muitos, incluindo:</p>
<ol type="1">
<li>uma melhor apreciação das relações marginais entre as variáveis (o que permite identificar, também, se variáveis explicativas estão relacionadas entre si… );<br>
</li>
<li><em>insight</em> a respeito de possíveis formas funcionais alternativas para a relação de regressão;<br>
</li>
<li>descoberta de erros e anomalias nos dados;<br>
</li>
<li>melhor compreensão de possíveis limitações que os dados impõe aos modelos que serão construídos.</li>
</ol>
<p>Note que parece existir algum tipo de relação estatística entre a resposta e cada uma das variáveis explicativas consideradas. Por exemplo, o rendimento dos automóveis observados parece ser, em geral, maior para modelos mais modernos do que para modelos mais antigos. Há alguns pares de variáveis explicativas que também relacionam-se entre si. Isso pode vir a trazer alguns problemas na estimação dos parâmetros dos modelos de regressão, mas retomaremos essa discussão no momento oportuno.</p>
<p>Podemos ainda examinar a relação entre duas variáveis, condicionando a uma outra variável categórica. Por exemplo, podemos construir um gráfico que evidencia a relação entre <code>mpg</code> e <code>hp</code>, para cada nível da variável <code>cylinder.</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto, <span class="fu">aes</span>(<span class="at">x =</span> hp, <span class="at">y =</span> mpg)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona pontos </span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (cores e símbolos distintos para diferentes classes da variável `cylinder`)</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> cylinder, <span class="at">shape =</span> cylinder)) <span class="sc">+</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona retas de tendência</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">color =</span> cylinder), <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As relações condicionais são representadas no gráfico por cores e símbolos distintos. Neste exemplo, não parece haver grande diferença no rendimento de motores de diferentes potências com 8 cilindros. Por outro lado, para motores com 4 cilindros, parece haver uma redução drástica no rendimento do automóvel, conforme aumenta a sua potência.</p>
<p>O diagrama de dispersão de <code>mpg</code> e <code>hp</code> sugere que a relação estatística entre essas duas variáveis não é linear. Quando isto ocorre, pode ser necessário realizar algum tipo de transformação nos dados.</p>
<p><strong>Transformações</strong></p>
<p>A relação estatística entre <code>mpg</code> e <code>hp</code> é curvilínea. Vejamos o resultado da aplicação de algumas transformações simples à variável <code>hp</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span> hp, <span class="at">y =</span> mpg), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">sqrt</span>(hp), <span class="at">y =</span> mpg), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span> <span class="dv">1</span><span class="sc">/</span>hp, <span class="at">y =</span> mpg), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">log2</span>(hp), <span class="at">y =</span> mpg), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>O primeiro gráfico mostra a relação original entre <code>mpg</code> e <code>hp</code>; no segundo, temos a raiz quadrada de <code>hp</code>; no terceiro, foi aplicada a transformação inversa; e, no último, temos o log (na base 2) de <code>hp</code>. A base da função logarítmica é irrelevante; apenas a interpretação é facilitada se utilizamos base 2, pois um acréscimo de uma unidade em ‘log(x)’ implica no dobro de ‘x’, enquanto que se estivermos utilizando a base natural, temos ‘x’ vezes ‘e’. Diferentes bases alteram apenas a constante de multiplicação.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="GED16_AULA01_Exemplo_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="1536"></p>
</div>
</div>
<p>Neste exemplo, há evidências de uma relação estatística linear positiva entre o rendimento e o inverso da potência do motor. Vamos verificar a correlação entre o par de variáveis <code>mpg</code> e <code>inv_hp</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coef. de correlacao</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span> (mpg, inv_hp)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8167671</code></pre>
</div>
</div>
<p>O valor do coeficiente correlação amostral suporta as observações realizadas a partir do gráfico de dispersão. Correlação elevada (~1) indica relação fortemente linear. Embora a correlação seja uma medida útil da direção e força da associação linear entre duas variáveis, não podemos utilizá-la para realizar, por exemplo, previsão. Além disto, a correlação mede apenas a força da relação <em>linear</em> para <em>um par</em> de variáveis.</p>
<p>Na próxima aula, poderemos proceder com o ajuste de um modelo de regressão linear simples para este par de variáveis.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>