<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Denys Derlian, João Vieira e Rafael Rocha">

<title>GED-16: Análise de Regressão</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/clipboard/clipboard.min.js"></script>
<script src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/quarto-html/quarto.js"></script>
<script src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/quarto-html/popper.min.js"></script>
<script src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/quarto-html/anchor.min.js"></script>
<link href="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">GED-16: Análise de Regressão</h1>
<p class="subtitle lead">AULA02: Prática (2o. semestre/2023)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Denys Derlian, João Vieira e Rafael Rocha </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">8 de agosto de 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<hr>
<section id="introdução" class="level1">
<h1>Introdução</h1>
<p>Os dados disponíveis no arquivo <code>data/owid.csv</code> foram obtidos do portal <a href="https://ourworldindata.org/">Our World in Data</a>, cuja missão é publicar pesquisas e dados relacionados a grandes problemas mundiais como pobreza, doenças, fome, mudanças climáticas, guerras, riscos existenciais e desigualdade.</p>
<p>Os dados originais foram pré-processados no sentido de remover observações faltantes. Há um total de 985 observações coletadas para 21 variáveis:</p>
<p><strong>Variáveis</strong></p>
<ol type="1">
<li><code>continent</code>: continente em que está o país</li>
<li><code>entity</code>: nome do país</li>
<li><code>code</code>: código do país</li>
<li><code>year</code>: ano</li>
<li><code>birth_rate</code>: número de nascimentos com vida por 1.000 habitantes na população.</li>
<li><code>child_mortality</code>: mortes de crianças menores de 5 anos de idade (% nascimentos)</li>
<li><code>co2_emission_pc</code>: emissões anuais de CO2 per capita (t/pessoa)</li>
<li><code>deaths_solid_fuels_pollution</code>: mortes resultantes de poluição por queima de combustíveis sólidos em ambientes internos (%)</li>
<li><code>deaths_particulate_pollution</code>: mortes resultantes de poluição por material particulado em ambientes externos (%)</li>
<li><code>deaths_air_pollution</code>: mortes resultantes de poluição do ar ambiente (%)</li>
<li><code>deaths_ozone</code>: mortes resultantes de poluição por ozônio em ambientes externos (%)</li>
<li><code>deaths_sanitation</code>: mortes resultantes de falta ou precariedade de acesso a saneamento básico (%)</li>
<li><code>electricity_demand</code>: geração total de eletricidade anual, ajustada por importação e exportação de eletricidade (TWh)</li>
<li><code>energy_use_pc</code>: consumo de energia médio anual (eletricidade, transporte, aquecimento, preparo de alimentos) per capita (KWh/pessoa)</li>
<li><code>expected_schooling</code>: expectativa do número de anos de educação que uma criança que entra no sistema escolar deve receber</li>
<li><code>happiness_cantril_ladder</code>: nível de felicidade médio populacional (0-10)</li>
<li><code>gdp_pc</code>: produto interno bruto per capita ($ internacional, referência 2017)</li>
<li><code>life_expectancy</code>: expectativa de vida no nascimento (anos)</li>
<li><code>milk_consumption_pc</code>: consumo de leite médio anual per capita (kg)</li>
<li><code>no_water</code>: população sem acesso a fontes seguras de água (encanada, poços, fontes, chuva e envasada) (%)</li>
<li><code>urban_population_percent</code>: população habitante de áreas urbanas (% população total)</li>
</ol>
<hr>
</section>
<section id="análise-exploratória-de-dados" class="level1">
<h1>Análise Exploratória de Dados</h1>
<section id="análise-preliminar-e-preparação-da-massa-de-dados" class="level2">
<h2 class="anchored" data-anchor-id="análise-preliminar-e-preparação-da-massa-de-dados">Análise Preliminar e Preparação da Massa de Dados</h2>
<p>Nesta seção, é conduzida a análise exploratória da massa de dados <code>owid</code>, a fim de compreender suas características principais. De modo geral, a ideia inicial é procurar por possíveis correlações entre a felicidade média da população e as demais variáveis.</p>
<p>Inicialmente, vamos limpar a área de trabalho e iniciar a leitura dos dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># limpa área de trabalho</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># carrega pacote `tidyverse`</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># carrega dados</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>owid <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"data/owid.csv"</span>, <span class="at">delim =</span> <span class="st">","</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># codifica variável `continent` como fator</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>owid<span class="sc">$</span>continent <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(owid<span class="sc">$</span>continent)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(owid)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [985 × 21] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ continent                   : Factor w/ 6 levels "Africa","Asia",..: 2 2 2 2 2 2 2 3 3 3 ...
 $ country_code                : chr [1:985] "AFG" "AFG" "AFG" "AFG" ...
 $ entity                      : chr [1:985] "Afghanistan" "Afghanistan" "Afghanistan" "Afghanistan" ...
 $ year                        : num [1:985] 2011 2014 2015 2016 2017 ...
 $ birth_rate                  : num [1:985] 39.9 39.1 38.8 37.9 37.3 ...
 $ child_mortality             : num [1:985] 7.43 6.51 6.32 6.11 5.75 5.91 5.53 1.58 1.42 1.37 ...
 $ co2_emission_pc             : num [1:985] 0.405 0.28 0.29 0.262 0.277 ...
 $ deaths_solid_fuels_pollution: num [1:985] 252 217 208 201 194 ...
 $ deaths_particulate_pollution: num [1:985] 41.3 53 54.3 53.7 53.3 ...
 $ deaths_air_pollution        : num [1:985] 295 270 264 256 250 ...
 $ deaths_ozone                : num [1:985] 5.11 4.93 5.15 5.44 5.79 5.11 5.05 1.08 1.06 0.87 ...
 $ deaths_sanitation           : num [1:985] 8.57 6.93 6.47 6.1 5.85 5 4.58 0.07 0.06 0.06 ...
 $ electricity_demand          : num [1:985] 3.03 4.87 4.96 5.54 5.88 6.16 5.98 7.41 7.75 7.24 ...
 $ energy_use_pc               : num [1:985] 1614 1024 1097 995 1027 ...
 $ expected_schooling          : num [1:985] 9.28 10.17 10.18 10.19 10.19 ...
 $ happiness_cantril_ladder    : num [1:985] 4.26 3.58 3.36 3.79 3.63 ...
 $ gdp_pc                      : num [1:985] 1961 2144 2109 2101 2096 ...
 $ life_expectancy             : num [1:985] 61.4 62.5 62.7 63.1 63 ...
 $ milk_consumption_pc         : num [1:985] 38.7 46.5 41 40 38.7 ...
 $ no_water                    : num [1:985] 44.6 37.5 35.1 32.8 30.4 ...
 $ urban_population_percent    : num [1:985] 23.9 24.6 24.8 25 25.2 ...
 - attr(*, "spec")=
  .. cols(
  ..   continent = col_character(),
  ..   country_code = col_character(),
  ..   entity = col_character(),
  ..   year = col_double(),
  ..   birth_rate = col_double(),
  ..   child_mortality = col_double(),
  ..   co2_emission_pc = col_double(),
  ..   deaths_solid_fuels_pollution = col_double(),
  ..   deaths_particulate_pollution = col_double(),
  ..   deaths_air_pollution = col_double(),
  ..   deaths_ozone = col_double(),
  ..   deaths_sanitation = col_double(),
  ..   electricity_demand = col_double(),
  ..   energy_use_pc = col_double(),
  ..   expected_schooling = col_double(),
  ..   happiness_cantril_ladder = col_double(),
  ..   gdp_pc = col_double(),
  ..   life_expectancy = col_double(),
  ..   milk_consumption_pc = col_double(),
  ..   no_water = col_double(),
  ..   urban_population_percent = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>Observamos, portanto, um total de 985 dados, sendo três colunas apresentadas como strings (<code>continent</code>, <code>entity</code> e <code>country_code</code>) e as demais como numéricas. Não obstante, os nomes das variáveis são intuitivos e não necessitam de alterações.</p>
<section id="dados-faltantes" class="level3">
<h3 class="anchored" data-anchor-id="dados-faltantes">Dados faltantes</h3>
<p>Agora, vamos verificar a presença de dados faltantes na base. Para isso, vamos utilizar o comando <code>summary()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># verifica nomes das variáveis</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(owid)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         continent   country_code          entity               year     
 Africa       :293   Length:985         Length:985         Min.   :2011  
 Asia         :240   Class :character   Class :character   1st Qu.:2014  
 Europe       :280   Mode  :character   Mode  :character   Median :2016  
 North America: 95                                         Mean   :2016  
 Oceania      : 14                                         3rd Qu.:2018  
 South America: 63                                         Max.   :2019  
   birth_rate    child_mortality  co2_emission_pc   
 Min.   : 5.92   Min.   : 0.200   Min.   : 0.02473  
 1st Qu.:11.20   1st Qu.: 0.580   1st Qu.: 0.76427  
 Median :18.40   Median : 1.610   Median : 2.77652  
 Mean   :20.85   Mean   : 3.049   Mean   : 4.62566  
 3rd Qu.:28.75   3rd Qu.: 4.730   3rd Qu.: 6.63869  
 Max.   :48.36   Max.   :15.410   Max.   :32.87282  
 deaths_solid_fuels_pollution deaths_particulate_pollution deaths_air_pollution
 Min.   :  0.00               Min.   :  2.48               Min.   :  2.66      
 1st Qu.:  0.28               1st Qu.: 20.18               1st Qu.: 29.95      
 Median : 11.21               Median : 34.35               Median : 80.30      
 Mean   : 50.50               Mean   : 44.52               Mean   : 96.29      
 3rd Qu.: 92.63               3rd Qu.: 63.66               3rd Qu.:157.51      
 Max.   :281.26               Max.   :200.29               Max.   :314.45      
  deaths_ozone    deaths_sanitation electricity_demand energy_use_pc     
 Min.   : 0.000   Min.   :  0.00    Min.   :   0.05    Min.   :   180.9  
 1st Qu.: 0.750   1st Qu.:  0.05    1st Qu.:   6.16    1st Qu.:  3623.2  
 Median : 1.410   Median :  0.56    Median :  16.21    Median : 15302.4  
 Mean   : 2.115   Mean   : 14.74    Mean   : 167.62    Mean   : 25020.4  
 3rd Qu.: 2.220   3rd Qu.: 22.27    3rd Qu.:  87.37    3rd Qu.: 33744.6  
 Max.   :35.430   Max.   :158.41    Max.   :7444.69    Max.   :188294.0  
 expected_schooling happiness_cantril_ladder     gdp_pc         life_expectancy
 Min.   : 4.983     Min.   :2.567            Min.   :   729.7   Min.   :49.95  
 1st Qu.:11.455     1st Qu.:4.517            1st Qu.:  4776.6   1st Qu.:65.46  
 Median :13.720     Median :5.302            Median : 13086.0   Median :73.57  
 Mean   :13.535     Mean   :5.403            Mean   : 19954.6   Mean   :71.96  
 3rd Qu.:15.585     3rd Qu.:6.208            3rd Qu.: 29877.0   3rd Qu.:78.41  
 Max.   :23.089     Max.   :7.856            Max.   :116283.7   Max.   :84.36  
 milk_consumption_pc    no_water      urban_population_percent
 Min.   :  0.1835    Min.   : 0.000   Min.   : 11.78          
 1st Qu.: 19.3253    1st Qu.: 0.230   1st Qu.: 42.73          
 Median : 74.3830    Median : 2.930   Median : 60.31          
 Mean   : 94.2947    Mean   : 8.778   Mean   : 59.32          
 3rd Qu.:153.9104    3rd Qu.:15.360   3rd Qu.: 77.38          
 Max.   :364.5135    Max.   :52.050   Max.   :100.00          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Posição dos dados faltantes:"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Posição dos dados faltantes:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">is.na</span>(owid))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>Portanto, percebemos que não há dados faltantes na base, conforme esperado da filtragem prévia realizada pela professora. Com isso, iremos prosseguir para a analise exploratória dos dados.</p>
</section>
<section id="resumos-gráficos" class="level3">
<h3 class="anchored" data-anchor-id="resumos-gráficos">Resumos gráficos</h3>
<p>Histograma de felicidade média populacional:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density))) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona linha de densidade estimada (suavização)</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="dv">4</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">fill =</span> <span class="dv">4</span>, <span class="at">alpha =</span> <span class="fl">0.25</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona dispersão unidimensional de `mpg`</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_rug</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Densidade de probabilidade de felicidade separado por cores para cada um dos continentes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Densidade por continente</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> happiness_cantril_ladder, <span class="at">fill =</span> continent)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">position =</span> <span class="st">"identity"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ao separar as densidades da variável felicidade por continente é possível verificar que o nível de felicidade das pessoas varia de acordo com o continente em que elas vivem.</p>
</section>
</section>
<section id="verificação-de-possíveis-variáveis-correlacionadas" class="level2">
<h2 class="anchored" data-anchor-id="verificação-de-possíveis-variáveis-correlacionadas">Verificação de possíveis variáveis correlacionadas</h2>
<p>Mesmo antes de observar os dados, conjectura-se que algumas variáveis possam ter maior correlação com o nível de felicidade da população. As variáveis escolhidas devido a uma suspeita de possuírem correlação com o nível de felicidade foram: acesso das pessoas a fontes seguras de água, mortalidade infantil, consumo de leite e pessoas vivendo com sistema sanitário precário. Assim, foram gerados os gráficos entre tais grandezas, de forma a verificar se existem correlações ou não.</p>
<p>Gráfico de dispersão para as variáveis felicidade e população sem acesso a fontes seguras de água.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualização</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagrama de dispersão</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> no_water, <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona pontos</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>É possível perceber uma correlação negativa entre as variáveis de falta de água e felicidade da população. Ao dividir os dados em cada um dos continentes é possível construir o seguinte gráfico:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualização</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagrama de dispersão</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> no_water, <span class="at">y =</span> happiness_cantril_ladder, <span class="at">color =</span> continent)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona pontos</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Percebe-se uma tendência de queda de felicidade quanto mais pessoas estão sem acesso a fontes seguras de água. É possível conjecturar também que em continentes como a África e a Asia a felicidade das pessoas é menos sensível a fontes seguras de água que nos demais continentes.</p>
<p>Um outro gráfico analisado é o de felicidade pela mortalidade infantil.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualização</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagrama de dispersão</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> child_mortality, <span class="at">y =</span> happiness_cantril_ladder, <span class="at">color =</span> continent)) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona pontos</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p>Também é possível perceber através das linhas de tendência que no continente africano a felicidade da população é menos sensível a variações da mortalidade infantil que nos outros continentes.</p>
<p>Uma outra análise feita foi da felicidade pelo consumo de leite da população e foi possível construir o seguinte gráfico:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualização</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagrama de dispersão</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> milk_consumption_pc, <span class="at">y =</span> happiness_cantril_ladder, <span class="at">color =</span> continent)) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona pontos</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ao observar os dados, aparentemente em todos os continentes um consumo maior de leite está correlacionado com uma maior felicidade da população com linhas de tendência de inclinações semelhantes. Porém, os dados aparentam estar muito dispersos das linhas de tendência, precisando assim de novas métricas para confirmar ou refutar uma correlação entre os dados.</p>
<p>Também foi gerado o gráfico de felicidade por mortes correlacionadas a um sistema sanitário precário.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualização</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagrama de dispersão</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> deaths_sanitation, <span class="at">y =</span> happiness_cantril_ladder, <span class="at">color =</span> continent)) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona pontos</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>É possível perceber um efeito semelhante das mortes por motivos sanitários se compararmos com a falta de acesso à fontes seguras de água e de mortalidade infantil. As variáveis aparentam estar correlacionadas e também aparenta que a sensibilidade da felicidade com relação a mortes por falta de saneamento é menor no continente africano se comparado aos demais.</p>
<hr>
</section>
</section>
<section id="análise-de-regressão" class="level1">
<h1>Análise de Regressão</h1>
<section id="parte-1" class="level2">
<h2 class="anchored" data-anchor-id="parte-1">Parte 1</h2>
<p>Assuma que um modelo de regressão linear simples é adequado para modelar a relação da variável de resposta <code>happiness_cantril_ladder</code> a cada uma das variáveis explicativas: <code>birth_rate</code>, <code>deaths_air_pollution</code>,<code>expected_schooling</code>, <code>life_expectancy</code>.</p>
<section id="construa-um-modelo-de-regressão-para-cada-um-desses-pares-de-variáveis" class="level3">
<h3 class="anchored" data-anchor-id="construa-um-modelo-de-regressão-para-cada-um-desses-pares-de-variáveis">Construa um modelo de regressão para cada um desses pares de variáveis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói modelo de regressão linear simples para taxa de natalidade</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>owid_rls_birth <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness_cantril_ladder <span class="sc">~</span> birth_rate, <span class="at">data =</span> owid)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável de resposta: happiness_cantril_ladder</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável explicativa: birth_rate</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>owid_rls_birth</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness_cantril_ladder ~ birth_rate, data = owid)

Coefficients:
(Intercept)   birth_rate  
    6.93486     -0.07347  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói modelo de regressão linear simples para mortes por poluição do ar</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>owid_rls_Dair <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness_cantril_ladder <span class="sc">~</span> deaths_air_pollution, <span class="at">data =</span> owid)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável de resposta: happiness_cantril_ladder</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável explicativa: deaths_air_pollution</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>owid_rls_Dair</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness_cantril_ladder ~ deaths_air_pollution, 
    data = owid)

Coefficients:
         (Intercept)  deaths_air_pollution  
             6.57286              -0.01215  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói modelo de regressão linear simples para expectativa de escolaridade.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>owid_rls_ExpSchool <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness_cantril_ladder <span class="sc">~</span> expected_schooling, <span class="at">data =</span> owid)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável de resposta: happiness_cantril_ladder</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável explicativa: expected_schooling</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>owid_rls_ExpSchool</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness_cantril_ladder ~ expected_schooling, data = owid)

Coefficients:
       (Intercept)  expected_schooling  
            1.6478              0.2774  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói modelo de regressão linear simples para expectativa de vida.</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>owid_rls_LifeExpec <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness_cantril_ladder <span class="sc">~</span> life_expectancy, <span class="at">data =</span> owid)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável de resposta: happiness_cantril_ladder</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável explicativa: life_expectancy</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>owid_rls_LifeExpec</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness_cantril_ladder ~ life_expectancy, data = owid)

Coefficients:
    (Intercept)  life_expectancy  
        -2.4828           0.1096  </code></pre>
</div>
</div>
</section>
<section id="construa-gráficos-de-dispersão-separados-com-as-retas-de-regressão-ajustadas-para-cada-caso" class="level3">
<h3 class="anchored" data-anchor-id="construa-gráficos-de-dispersão-separados-com-as-retas-de-regressão-ajustadas-para-cada-caso">Construa gráficos de dispersão (separados) com as retas de regressão ajustadas para cada caso</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gera gráfico de dispersão para taxa de natalidade</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> birth_rate, <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gera gráfico de dispersão para taxa de mortes por poluição do ar</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> deaths_air_pollution, <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gera gráfico de dispersão para taxa de natalidade</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> expected_schooling, <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-12-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gera gráfico de dispersão para expectativa de vida</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> life_expectancy, <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-12-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Interpretando os modelos utilizados, temos que as retas de regressão que melhor se aproxima, para descrever a dependência entre as grandezas selecionadas duas a duas são:</p>
<ul>
<li><p>Felicidade x Taxa de natalidade:<br>
happiness_cantril_ladder = 6.93 + -0.07 *birth_rate</p></li>
<li><p>Felicidade x Mortes por poluição do ar: happiness_cantril_ladder = 6.57 + -0.01 *deaths_air_pollution</p></li>
<li><p>Felicidade x Expectativa de escolaridade: happiness_cantril_ladder = 1.65 + 0.28 *expected_schooling</p></li>
<li><p>Felicidade x Expectativa de vida: happiness_cantril_ladder = -2.48 + 0.11 *life_expectancy</p></li>
</ul>
<p>Colocando em um ambiente com os números escritos expressamente:</p>
<ul>
<li>Taxa de Natalidade</li>
</ul>
<p>Modelo: <span class="math inline">\(happiness\_cantril\_ladder = -0.07347 \cdot birth\_rate + 6.93486\)</span></p>
<ul>
<li>Mortes por Poluição do Ar</li>
</ul>
<p>Modelo: <span class="math inline">\(happiness\_cantril\_ladder = -0.01215 \cdot deaths\_air\_pollution + 6.57286\)</span></p>
<ul>
<li>Expectativa de Escolaridade</li>
</ul>
<p>Modelo: <span class="math inline">\(happiness\_cantril\_ladder = 0.2774 \cdot expected\_schooling + 1.6478\)</span></p>
<ul>
<li>Expectativa de Vida</li>
</ul>
<p>Modelo: <span class="math inline">\(happiness\_cantril\_ladder = 0.1096 \cdot life\_expectancy - 2.4828\)</span></p>
</section>
<section id="obtenha-o-mse-para-cada-modelo.-que-variável-explicativa-produz-menor-variabilidade-em-torno-da-reta-de-regressão-ajustada" class="level3">
<h3 class="anchored" data-anchor-id="obtenha-o-mse-para-cada-modelo.-que-variável-explicativa-produz-menor-variabilidade-em-torno-da-reta-de-regressão-ajustada">Obtenha o MSE para cada modelo. Que variável explicativa produz menor variabilidade em torno da reta de regressão ajustada?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MSE para taxa de natalidade</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"O MSE para taxa de natalidade é:"</span>, <span class="fu">mean</span>(owid_rls_birth<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "O MSE para taxa de natalidade é: 0.666798670114976"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MSE para mortes por poluição do ar</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"O MSE para mortes por poluição do ar é:"</span>, <span class="fu">mean</span>(owid_rls_Dair<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "O MSE para mortes por poluição do ar é: 0.486220082192863"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MSE para expectativa de escolaridade</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"O MSE para expectativa de escolaridade é:"</span>, <span class="fu">mean</span>(owid_rls_ExpSchool<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "O MSE para expectativa de escolaridade é: 0.580257951083663"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MSE para expectativa de vida"</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"O MSE para expectativa de vida é:"</span>, <span class="fu">mean</span>(owid_rls_LifeExpec<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "O MSE para expectativa de vida é: 0.490668226126506"</code></pre>
</div>
</div>
<p>Dessa forma, percebemos que o menor MSE é para a variável <code>deaths_air_pollution</code>, ou seja, a variável que melhor se ajusta ao modelo de regressão linear simples é a taxa de mortes por poluição do ar. Isso indica que o modelo de regressão linear utilizando “mortes por poluição do ar” como variável explicativa tem um menor erro médio quadrático em relação aos dados reais, o que sugere que a variabilidade em torno da reta de regressão ajustada é menor para essa variável em comparação com as outras variáveis explicativas.</p>
</section>
<section id="utilizando-r2-como-critério-qual-das-variáveis-explicativas-contribui-para-a-maior-redução-na-variabilidade-da-resposta-happiness_cantril_ladder" class="level3">
<h3 class="anchored" data-anchor-id="utilizando-r2-como-critério-qual-das-variáveis-explicativas-contribui-para-a-maior-redução-na-variabilidade-da-resposta-happiness_cantril_ladder">Utilizando R2 como critério, qual das variáveis explicativas contribui para a maior redução na variabilidade da resposta <code>happiness_cantril_ladder</code>?</h3>
<p>Avaliando agora a relação de R² ajustado para cada par de variáveis, temos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R² ajustado para taxa de natalidade</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"R² ajustado para taxa de natalidade"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R² ajustado para taxa de natalidade"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(owid_rls_birth)<span class="sc">$</span>adj.r.squared</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.475617</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R² ajustado para mortes por poluição do ar</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"R² ajustado para mortes por poluição do ar"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R² ajustado para mortes por poluição do ar"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(owid_rls_Dair)<span class="sc">$</span>adj.r.squared</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6176274</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R² ajustado para expectativa de escolaridade</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"R² ajustado para expectativa de escolaridade"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R² ajustado para expectativa de escolaridade"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(owid_rls_ExpSchool)<span class="sc">$</span>adj.r.squared</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5436742</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R² ajustado para expectativa de vida</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"R² ajustado para expectativa de vida"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R² ajustado para expectativa de vida"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(owid_rls_LifeExpec)<span class="sc">$</span>adj.r.squared</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6141293</code></pre>
</div>
</div>
<p>Não obstante, a melhor correlação, segundo o critério de R² ajustado, ainda sim é dada para a variável <code>deaths_air_pollution</code>, ou seja, a variável que melhor se ajusta ao modelo de regressão linear simples é a relação de mortes por poluição do ar (por 100.000).</p>
<hr>
</section>
</section>
<section id="parte-2" class="level2">
<h2 class="anchored" data-anchor-id="parte-2">Parte 2</h2>
<p>Para cada nível da variável categórica <code>continent</code>, construa um modelo de regressão para a variável de resposta <code>happiness_cantril_ladder</code> em função da variável escolhida no último item da questão anterior. Assuma que o modelo de 1a. ordem é adequado para modelar essas relações.</p>
<section id="obtenha-os-modelos-de-regressão-ajustados.-as-funções-de-regressão-estimadas-são-semelhantes-para-todos-os-níveis-da-variável-continent-discuta." class="level3">
<h3 class="anchored" data-anchor-id="obtenha-os-modelos-de-regressão-ajustados.-as-funções-de-regressão-estimadas-são-semelhantes-para-todos-os-níveis-da-variável-continent-discuta.">Obtenha os modelos de regressão ajustados. As funções de regressão estimadas são semelhantes para todos os níveis da variável <code>continent</code>? Discuta.</h3>
<p>Vamos refazer as análises passadas as variáveis por continente somente para a variável “deaths_air_pollution”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>continentes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Africa"</span>, <span class="st">"Asia"</span>, <span class="st">"Europe"</span>, <span class="st">"North America"</span>, <span class="st">"Oceania"</span>, <span class="st">"South America"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>grandezas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"deaths_air_pollution"</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>regressoes <span class="ot">&lt;-</span> <span class="fu">matrix</span>()</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Cria dataframes para cada continente</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> continentes) {</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Continente: "</span>, i))</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>    df_per_continent <span class="ot">&lt;-</span> owid <span class="sc">%&gt;%</span> <span class="fu">filter</span>(continent <span class="sc">==</span> i)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>    temporary <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (metrica <span class="cf">in</span> grandezas) {</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>        regressao <span class="ot">&lt;-</span> <span class="fu">lm</span>(df_per_continent<span class="sc">$</span>happiness_cantril_ladder <span class="sc">~</span> df_per_continent[[metrica]])</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>        temporary <span class="ot">&lt;-</span> temporary <span class="sc">%&gt;%</span> <span class="fu">append</span>(regressao)</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>        newPlot <span class="ot">&lt;-</span> df_per_continent <span class="sc">%&gt;%</span></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .data[[metrica]], <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>            <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>        <span class="fu">print</span>(newPlot)</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>    regressoes <span class="ot">&lt;-</span> <span class="fu">rbind</span>(regressoes, temporary)</span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="st">"----------------------------------------------------------------"</span>)</span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Continente:  Africa"</code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "----------------------------------------------------------------"
[1] "Continente:  Asia"</code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "----------------------------------------------------------------"
[1] "Continente:  Europe"</code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "----------------------------------------------------------------"
[1] "Continente:  North America"</code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "----------------------------------------------------------------"
[1] "Continente:  Oceania"</code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-15-5.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "----------------------------------------------------------------"
[1] "Continente:  South America"</code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-15-6.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "----------------------------------------------------------------"</code></pre>
</div>
</div>
<p>Temos agora, além dos dados visuais para os gráficos avaliados, uma matriz <code>regressoes</code> com os dados de cada regressão linear simples com as colunas representando cada variável e as linhas, cada continente. Verifica-se que as funções de regressão estimadas não são semelhantes para todos os níveis da variável <code>continent</code>. Tome, por exemplo, que para <code>Europe</code> e <code>North America</code>, a inclinação descendente é mais acentuada que para outros países, enquanto para a <code>Oceania</code>, a inclinação é positiva.</p>
<p>Vamos avaliar então, para cada continente, se os modelos de regressão assumem erros semelhantes.</p>
</section>
<section id="obtenha-o-mse-para-cada-nível-da-variável-continent.-a-variabilidade-em-torno-da-reta-de-regressão-ajustada-é-semelhante-para-todos-os-níveis" class="level3">
<h3 class="anchored" data-anchor-id="obtenha-o-mse-para-cada-nível-da-variável-continent.-a-variabilidade-em-torno-da-reta-de-regressão-ajustada-é-semelhante-para-todos-os-níveis">Obtenha o MSE para cada nível da variável <code>continent</code>. A variabilidade em torno da reta de regressão ajustada é semelhante para todos os níveis?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> continentes) {</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Continente: "</span>, i))</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>df_per_continent <span class="ot">&lt;-</span> owid <span class="sc">%&gt;%</span> <span class="fu">filter</span>(continent <span class="sc">==</span> i)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co"># df_per_continent %&gt;% head(10) %&gt;% print()</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(owid_rls_birth)$adj.r.squared</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>metrica <span class="ot">&lt;-</span> grandezas[<span class="dv">1</span>]</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>regressao <span class="ot">&lt;-</span> <span class="fu">lm</span>(df_per_continent<span class="sc">$</span>happiness_cantril_ladder <span class="sc">~</span> df_per_continent[[metrica]])</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"O MSE associado a variável"</span>, metrica, <span class="st">"é de"</span>, <span class="fu">round</span>(<span class="fu">mean</span>(regressao<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>), <span class="dv">4</span>), <span class="st">", conforme o modelo:"</span>))</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>temporary <span class="ot">&lt;-</span> temporary <span class="sc">%&gt;%</span> <span class="fu">append</span>(regressao)</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(regressao)</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>newPlot <span class="ot">&lt;-</span> df_per_continent <span class="sc">%&gt;%</span></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .data[[metrica]], <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) </span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(newPlot)</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Continente:  Africa"
[1] "O MSE associado a variável deaths_air_pollution é de 0.2692 , conforme o modelo:"

Call:
lm(formula = df_per_continent$happiness_cantril_ladder ~ df_per_continent[[metrica]])

Coefficients:
                (Intercept)  df_per_continent[[metrica]]  
                   5.486803                    -0.007128  </code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Continente:  Asia"
[1] "O MSE associado a variável deaths_air_pollution é de 0.501 , conforme o modelo:"

Call:
lm(formula = df_per_continent$happiness_cantril_ladder ~ df_per_continent[[metrica]])

Coefficients:
                (Intercept)  df_per_continent[[metrica]]  
                   6.019702                    -0.006096  </code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Continente:  Europe"
[1] "O MSE associado a variável deaths_air_pollution é de 0.3959 , conforme o modelo:"

Call:
lm(formula = df_per_continent$happiness_cantril_ladder ~ df_per_continent[[metrica]])

Coefficients:
                (Intercept)  df_per_continent[[metrica]]  
                    6.98089                     -0.02375  </code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Continente:  North America"
[1] "O MSE associado a variável deaths_air_pollution é de 0.2351 , conforme o modelo:"

Call:
lm(formula = df_per_continent$happiness_cantril_ladder ~ df_per_continent[[metrica]])

Coefficients:
                (Intercept)  df_per_continent[[metrica]]  
                    7.02874                     -0.01491  </code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-16-4.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Continente:  Oceania"
[1] "O MSE associado a variável deaths_air_pollution é de 0.0015 , conforme o modelo:"

Call:
lm(formula = df_per_continent$happiness_cantril_ladder ~ df_per_continent[[metrica]])

Coefficients:
                (Intercept)  df_per_continent[[metrica]]  
                    7.16711                      0.03093  </code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-16-5.png" class="img-fluid" width="288"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Continente:  South America"
[1] "O MSE associado a variável deaths_air_pollution é de 0.1175 , conforme o modelo:"

Call:
lm(formula = df_per_continent$happiness_cantril_ladder ~ df_per_continent[[metrica]])

Coefficients:
                (Intercept)  df_per_continent[[metrica]]  
                    6.53651                     -0.01039  </code></pre>
</div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-16-6.png" class="img-fluid" width="288"></p>
</div>
</div>
</section>
<section id="construa-intervalos-de-confiança-95-para-o-coeficiente-angular-da-reta-de-regressão-para-os-continentes-north-america-e-south-america.-as-retas-de-regressão-para-os-diferentes-níveis-parecem-ter-mesma-inclinação-o-que-se-pode-concluir" class="level3">
<h3 class="anchored" data-anchor-id="construa-intervalos-de-confiança-95-para-o-coeficiente-angular-da-reta-de-regressão-para-os-continentes-north-america-e-south-america.-as-retas-de-regressão-para-os-diferentes-níveis-parecem-ter-mesma-inclinação-o-que-se-pode-concluir">Construa intervalos de confiança 95% para o coeficiente angular da reta de regressão para os continentes <code>North America</code> e <code>South America</code>. As retas de regressão para os diferentes níveis parecem ter mesma inclinação? O que se pode concluir?</h3>
<p>Construindo intervalos de confiança para os coeficientes angulares com os dados dos continentes “North America” e “South America”, temos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separando os dados para os continentes "North America" e "South America"</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>df_north_america <span class="ot">&lt;-</span> owid <span class="sc">%&gt;%</span> <span class="fu">filter</span>(continent <span class="sc">==</span> <span class="st">"North America"</span>)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>df_south_america <span class="ot">&lt;-</span> owid <span class="sc">%&gt;%</span> <span class="fu">filter</span>(continent <span class="sc">==</span> <span class="st">"South America"</span>)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando os modelos de regressão entre as variáveis deaths_air_pollution e happiness_cantril_ladder</span></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>deaths_air_pollution_north <span class="ot">&lt;-</span> df_north_america<span class="sc">$</span>deaths_air_pollution</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>lm_north <span class="ot">&lt;-</span> <span class="fu">lm</span>(df_north_america<span class="sc">$</span>happiness_cantril_ladder <span class="sc">~</span> deaths_air_pollution_north)</span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>deaths_air_pollution_south <span class="ot">&lt;-</span> df_south_america<span class="sc">$</span>deaths_air_pollution</span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a>lm_south <span class="ot">&lt;-</span> <span class="fu">lm</span>(df_south_america<span class="sc">$</span>happiness_cantril_ladder <span class="sc">~</span> deaths_air_pollution_south)</span>
<span id="cb68-16"><a href="#cb68-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-17"><a href="#cb68-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-18"><a href="#cb68-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalos de confiança para os coeficientes angulares</span></span>
<span id="cb68-19"><a href="#cb68-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-20"><a href="#cb68-20" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.lm</span>(lm_north,<span class="at">level=</span><span class="fl">0.95</span>, <span class="at">parm =</span> <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                 2.5 %      97.5 %
deaths_air_pollution_north -0.01682869 -0.01299155</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.lm</span>(lm_south,<span class="at">level=</span><span class="fl">0.95</span>, <span class="at">parm =</span> <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                 2.5 %       97.5 %
deaths_air_pollution_south -0.01477535 -0.006005369</code></pre>
</div>
</div>
<p>Assim, é possível perceber que o intervalo de confiança do coeficiente angular para a América do Norte se sobrepõe com o da América do Sul. Isso é percebido pois os intervalos de confiança 95% possuem intersecção. Portanto, pode-se concluir que os intervalos de confiança indicam que as inclinações das retas de regressão para a relação entre a variável <code>deaths_air_pollution</code> e a variável de resposta <code>happiness_cantril_ladder</code> não parecem ser significativamente diferentes entre <code>North America</code> e <code>South America</code>. Isso sugere que a relação entre essas variáveis pode ser semelhante nos dois continentes.</p>
</section>
<section id="construa-intervalos-de-confiança-para-a-resposta-esperada-correspondendo-a-deaths_air_pollution-50-para-os-continentes-north-america-e-south-america.-o-que-se-pode-concluir" class="level3">
<h3 class="anchored" data-anchor-id="construa-intervalos-de-confiança-para-a-resposta-esperada-correspondendo-a-deaths_air_pollution-50-para-os-continentes-north-america-e-south-america.-o-que-se-pode-concluir">Construa intervalos de confiança para a resposta esperada correspondendo a <code>deaths_air_pollution</code> = 50, para os continentes <code>North America</code> e <code>South America</code>. O que se pode concluir?</h3>
<p>Construindo intervalos de confiança para a resposta esperada da variável <code>happiness_cantril_ladder</code> para o valor da variável <code>deaths_air_pollution</code> = 50.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># valor de 50 para a variável deaths_air_pollution</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>Xn <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">deaths_air_pollution_north =</span> <span class="dv">50</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>Xs <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">deaths_air_pollution_south =</span> <span class="dv">50</span>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Construção dos intervalos de confiança 95%</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>ic_north <span class="ot">&lt;-</span> <span class="fu">predict.lm</span>(lm_north, <span class="at">newdata =</span> Xn, <span class="at">interval=</span><span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>ic_south <span class="ot">&lt;-</span> <span class="fu">predict.lm</span>(lm_south, <span class="at">newdata =</span> Xs, <span class="at">interval=</span><span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>result_line_north <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"North America: fit ="</span>, ic_north[<span class="dv">1</span>], <span class="st">"lower bound ="</span>, ic_north[<span class="dv">2</span>], <span class="st">"upper bound ="</span>, ic_north[<span class="dv">3</span>])</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>result_line_south <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"South America: fit ="</span>, ic_south[<span class="dv">1</span>], <span class="st">"lower bound ="</span>, ic_south[<span class="dv">2</span>], <span class="st">"upper bound ="</span>, ic_south[<span class="dv">3</span>])</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_line_north)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "North America: fit = 6.28323694134475 lower bound = 6.18121052150595 upper bound = 6.38526336118355"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_line_south)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "South America: fit = 6.0169948836722 lower bound = 5.91865734245674 upper bound = 6.11533242488766"</code></pre>
</div>
</div>
<p>Assim, os valores ajustados para os intervalos de confiança foram de 6.28 e 6.02 para a América do Norte e América do Sul, respectivamente. Já os intervalos de confiança para a América do Norte e América do Sul foram (6.18 ,6.39) e (5.92 ,6.12), respectivamente.</p>
<p>Comparando esses intervalos, podemos dizer que o intervalo de confiança para North America é um pouco mais amplo, indicando uma maior incerteza na estimativa da felicidade em comparação com South America. Isso pode sugerir que a relação entre <code>deaths_air_pollution</code> e <code>happiness_cantril_ladder</code> pode ser mais estável ou menos variável em South America em comparação com North America, para esse valor específico de <code>deaths_air_pollution</code>.</p>
<p>A falta de sobreposição nos intervalos de confiança sugere que existe uma diferença estatisticamente significativa nas estimativas da felicidade média para diferentes níveis de poluição do ar nos continentes North America e South America. Isso indica que a relação entre a variável <code>deaths_air_pollution</code> e a variável de resposta <code>happiness_cantril_ladder</code> varia entre esses continentes, implicando uma possível influência diferenciada da poluição do ar na felicidade entre as regiões geográficas, conforme analisado no contexto do modelo de regressão.</p>
</section>
<section id="construa-intervalos-de-previsão-para-uma-nova-observação-de-cada-continente-north-america-e-south-america-que-tenha-deaths_air_pollution-50.-o-que-se-pode-concluir" class="level3">
<h3 class="anchored" data-anchor-id="construa-intervalos-de-previsão-para-uma-nova-observação-de-cada-continente-north-america-e-south-america-que-tenha-deaths_air_pollution-50.-o-que-se-pode-concluir">Construa intervalos de previsão para uma nova observação de cada continente (<code>North America</code> e <code>South America</code>) que tenha <code>deaths_air_pollution</code> = 50. O que se pode concluir?</h3>
<p>Construindo intervalos de previsão para uma realização da variável <code>happiness_cantril_ladder</code> para o valor da variável <code>deaths_air_pollution</code> = 50.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construção de intervalos de previsão</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>ip_north <span class="ot">&lt;-</span> <span class="fu">predict.lm</span>(lm_north, <span class="at">newdata =</span> Xn, <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>ip_south <span class="ot">&lt;-</span> <span class="fu">predict.lm</span>(lm_south, <span class="at">newdata =</span> Xs, <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>result_line_northp <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"North America: fit ="</span>, ip_north[<span class="dv">1</span>], <span class="st">"lower bound ="</span>, ip_north[<span class="dv">2</span>], <span class="st">"upper bound ="</span>, ip_north[<span class="dv">3</span>])</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>result_line_southp <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"South America: fit ="</span>, ip_south[<span class="dv">1</span>], <span class="st">"lower bound ="</span>, ip_south[<span class="dv">2</span>], <span class="st">"upper bound ="</span>, ip_south[<span class="dv">3</span>])</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_line_northp)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "North America: fit = 6.28323694134475 lower bound = 5.30466737357636 upper bound = 7.26180650911314"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_line_southp)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "South America: fit = 6.0169948836722 lower bound = 5.31364920105787 upper bound = 6.72034056628653"</code></pre>
</div>
</div>
<p>Os valores para a estimativa pontual foram de 6.28 e 6.02 para a América do Norte e América do Sul, respectivamente. Já os intervalos de previsão para a América do Norte e América do Sul foram (5.3 ,7.26) e (5.31 ,6.72), respectivamente.</p>
<p>Ao comparar os intervalos de previsão para os cenários de <code>North America</code> e <code>South America</code>, observa-se uma sobreposição nos intervalos, indicando incerteza compartilhada nas estimativas de felicidade média entre os continentes. O intervalo para <code>North America</code> é ligeiramente mais amplo, sugerindo maior incerteza nessa estimativa em comparação com <code>South America</code>. Embora haja uma diferença nas estimativas pontuais de felicidade, a sobreposição dos intervalos ressalta a necessidade de cautela na interpretação, indicando que as variações podem não ser estatisticamente significativas.</p>
</section>
</section>
<section id="parte-3" class="level2">
<h2 class="anchored" data-anchor-id="parte-3">Parte 3</h2>
<p>Construa um modelo de regressão para a variável de resposta <code>happiness_cantril_ladder</code> em função de <code>gdp_pc</code>. Assuma que o modelo de 1a. ordem é adequado para modelar essas relações. Faz sentido aplicar alguma transformação à variável explicativa? Replique os procedimentos realizados no item (1) para um modelo considerando a variável explicativa em sua forma original ou transformada.</p>
<p>Inicia-se construindo o modelo de regressão para a variavel especificada normalmente repetindo os passos do item (1), sendo gerado o modelo linear, o gráfico, MSE e o valor de <span class="math inline">\(R^2\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói modelo de regressão linear simples para gdp_pc</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>owid_rls_gdp <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness_cantril_ladder <span class="sc">~</span> gdp_pc, <span class="at">data =</span> owid)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável de resposta: happiness_cantril_ladder</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável explicativa: gdp_pc</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>owid_rls_gdp</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness_cantril_ladder ~ gdp_pc, data = owid)

Coefficients:
(Intercept)       gdp_pc  
  4.504e+00    4.506e-05  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gera gráfico de dispersão para gdp_pc</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid, <span class="fu">aes</span>(<span class="at">x =</span> gdp_pc, <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"MSE para gdp_pc </span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MSE para gdp_pc </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(owid_rls_gdp<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5015186</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir o coeficiente de determinação ajustado (R²)</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Coeficiente de Determinação Ajustado (R²): </span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de Determinação Ajustado (R²): </code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(owid_rls_gdp)<span class="sc">$</span>adj.r.squared</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6055963</code></pre>
</div>
</div>
<p>Com base na inspeção visual do gráfico gerado e do coeficiente de determinação ajustado (R²) baixo, o modelo linear atual utilizando a variável explicativa <code>gdp_pc</code> não é capaz de explicar adequadamente a variabilidade na variável de resposta <code>happiness_cantril_ladder</code>. Isso indica que a relação entre essas variáveis não pode ser bem representada por um modelo linear simples. Podemos tentar algumas transformações a partir de uma aproximação inicial usando a função <code>cor</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>owid <span class="sc">|&gt;</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">cor</span>(happiness_cantril_ladder, <span class="dv">1</span><span class="sc">/</span>gdp_pc))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `cor(happiness_cantril_ladder, 1/gdp_pc)`
                                      &lt;dbl&gt;
1                                    -0.648</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>owid <span class="sc">|&gt;</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">cor</span>(happiness_cantril_ladder, <span class="fu">log</span>(gdp_pc)))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `cor(happiness_cantril_ladder, log(gdp_pc))`
                                         &lt;dbl&gt;
1                                        0.822</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>owid <span class="sc">|&gt;</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">cor</span>(happiness_cantril_ladder, <span class="fu">sqrt</span>(gdp_pc)))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `cor(happiness_cantril_ladder, sqrt(gdp_pc))`
                                          &lt;dbl&gt;
1                                         0.829</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>owid <span class="sc">|&gt;</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">cor</span>(happiness_cantril_ladder, <span class="fu">sqrt</span>(<span class="fu">sqrt</span>(gdp_pc))))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `cor(happiness_cantril_ladder, sqrt(sqrt(gdp_pc)))`
                                                &lt;dbl&gt;
1                                               0.833</code></pre>
</div>
</div>
<p>Nota-se a melhor correlação para a transformação <code>sqrt(sqrt(gdp_pc))</code>. Agora, repetem-se os passos do item (1):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>owid_gdp4 <span class="ot">&lt;-</span> owid <span class="sc">|&gt;</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gdp4  =</span> <span class="fu">sqrt</span>(<span class="fu">sqrt</span>(gdp_pc))) </span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói modelo de regressão linear simples para sqrt(sqrt(gdp_pc))</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>owid_rls_gdp4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness_cantril_ladder <span class="sc">~</span> gdp4, <span class="at">data =</span> owid_gdp4)</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável de resposta: happiness_cantril_ladder</span></span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Variável explicativa: sqrt(sqrt(gdp_pc))</span></span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a>owid_rls_gdp4</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness_cantril_ladder ~ gdp4, data = owid_gdp4)

Coefficients:
(Intercept)         gdp4  
     1.9922       0.3164  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gera gráfico de dispersão para gdp_pc</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(owid_gdp4, <span class="fu">aes</span>(<span class="at">x =</span> gdp4, <span class="at">y =</span> happiness_cantril_ladder)) <span class="sc">+</span></span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DENYS-DERLIAN_JOAO-VIEIRA_RAFAEL-ROCHA_EXERCICIO-S02_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"MSE para gdp_pc </span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MSE para gdp_pc </code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(owid_rls_gdp4<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3886452</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir o coeficiente de determinação ajustado (R²)</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Coeficiente de Determinação Ajustado (R²): </span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de Determinação Ajustado (R²): </code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(owid_rls_gdp4)<span class="sc">$</span>adj.r.squared</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6943621</code></pre>
</div>
</div>
<p>Os resultados indicam uma melhoria no desempenho do modelo após a transformação da variável explicativa <strong><code>gdp_pc</code></strong>. A redução no MSE de 0.5015186 para 0.3886452 e o aumento de R² de 0.6055963 para 0.6943621 são indicativos de um modelo mais apropriado e com melhor ajuste aos dados após a transformação. Isso sugere que a relação entre <strong><code>gdp_pc</code></strong> e <strong><code>happiness_cantril_ladder</code></strong> pode ser mais bem capturada através da transformação <strong><code>x = sqrt(sqrt(gdp_pc))</code></strong>, o que resulta em uma relação mais linear entre as variáveis. Portanto, a transformação parece ter melhorado a capacidade do modelo de explicar a variabilidade na felicidade com base no PIB per capita.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>