<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Denise B. Ferrari">

<title>GED-16: Análise de Regressão</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="GED16_AULA02_Exemplo_files/libs/clipboard/clipboard.min.js"></script>
<script src="GED16_AULA02_Exemplo_files/libs/quarto-html/quarto.js"></script>
<script src="GED16_AULA02_Exemplo_files/libs/quarto-html/popper.min.js"></script>
<script src="GED16_AULA02_Exemplo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GED16_AULA02_Exemplo_files/libs/quarto-html/anchor.min.js"></script>
<link href="GED16_AULA02_Exemplo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GED16_AULA02_Exemplo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GED16_AULA02_Exemplo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GED16_AULA02_Exemplo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GED16_AULA02_Exemplo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">GED-16: Análise de Regressão</h1>
<p class="subtitle lead">AULA02: Exemplo (1o. semestre/2023)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Denise B. Ferrari </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">15 de março de 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introdução" class="level2">
<h2 class="anchored" data-anchor-id="introdução">Introdução</h2>
<p>Exemplo “Consumo de Combustível de Automóveis”, retirado do <a href="https://archive.ics.uci.edu/ml/datasets/auto+mpg">UCI Machine Learning Repository</a>.</p>
<p>O objetivo inicial desse estudo era prever o consumo de combustível de automóveis em ambiente urbano (expresso em milhas por galão, mpg), a partir de algumas características do veículo.</p>
<p>Há um total de 398 observações registradas para 9 variáveis de interesse,<br>
incluindo a resposta <code>mpg</code>:</p>
<p><strong>Variáveis</strong></p>
<p><code>mpg</code>: numérica (contínua)<br>
<code>cylinder</code>: categórica (ordinal)<br>
<code>displacement</code>: numérica (contínua)<br>
<code>hp</code>: numérica (contínua)<br>
<code>weight</code>: numérica (contínua)<br>
<code>acceleration</code>: numérica (contínua)<br>
<code>modelyear</code>: numérica (discreta)<br>
<code>origin</code>: categórica (nominal)<br>
<code>carname</code>: categórica (nominal)</p>
<section id="parte-1-preparação-da-massa-de-dados" class="level3">
<h3 class="anchored" data-anchor-id="parte-1-preparação-da-massa-de-dados">PARTE 1: Preparação da Massa de Dados</h3>
<p>A análise completa está disponível no Exemplo da AULA01.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carrega os dados em uma tabela</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>auto <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/AutoMPG/auto-mpg.data"</span>, <span class="at">header =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Atribui nomes às variáveis (colunas da tabela)</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(auto) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"mpg"</span>, <span class="st">"cylinder"</span>, <span class="st">"displacement"</span>, <span class="st">"hp"</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"weight"</span>, <span class="st">"acceleration"</span>, <span class="st">"modelyear"</span>, <span class="st">"origin"</span>, <span class="st">"carname"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Codifica adequadamente variáveis quantitativas (numéricas) e categóricas (fatores)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># usando funções do pacote `tidyverse`:</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>auto <span class="ot">&lt;-</span> auto <span class="sc">%&gt;%</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"mpg"</span>, <span class="st">"displacement"</span>, <span class="st">"hp"</span>, </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>              <span class="st">"weight"</span>, <span class="st">"acceleration"</span>, <span class="st">"modelyear"</span>), as.numeric) <span class="sc">%&gt;%</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"cylinder"</span>, <span class="st">"origin"</span>), as.factor) <span class="sc">%&gt;%</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="st">"carname"</span>, as.character)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove linhas correspondentes às obs. faltantes da variável `hp`</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>auto <span class="ot">&lt;-</span> auto <span class="sc">%&gt;%</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># verifica estrutura dos dados</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(auto)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   392 obs. of  9 variables:
 $ mpg         : num  18 15 18 16 17 15 14 14 14 15 ...
 $ cylinder    : Factor w/ 5 levels "3","4","5","6",..: 5 5 5 5 5 5 5 5 5 5 ...
 $ displacement: num  307 350 318 304 302 429 454 440 455 390 ...
 $ hp          : num  130 165 150 150 140 198 220 215 225 190 ...
 $ weight      : num  3504 3693 3436 3433 3449 ...
 $ acceleration: num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
 $ modelyear   : num  70 70 70 70 70 70 70 70 70 70 ...
 $ origin      : Factor w/ 3 levels "1","2","3": 1 1 1 1 1 1 1 1 1 1 ...
 $ carname     : chr  "chevrolet chevelle malibu" "buick skylark 320" "plymouth satellite" "amc rebel sst" ...</code></pre>
</div>
</div>
<p>No Exemplo da AULA01, encontramos evidências visuais de uma relação estatística linear positiva entre o rendimento, dado pela variável <code>mpg</code> e o inverso da potência do motor <code>1/hp</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gera gráfico de dispersão de `mpg` vs. `1/hp`</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">/</span>hp, <span class="at">y =</span> mpg)) </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA02_Exemplo_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vamos verificar a correlação entre o par de variáveis <code>mpg</code> e <code>1/hp</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>auto <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Coeficiente de correlação</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">cor</span> (mpg, <span class="dv">1</span><span class="sc">/</span>hp))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cor(mpg, 1/hp)
1      0.8167671</code></pre>
</div>
</div>
<p>O valor do coeficiente correlação amostral suporta as observações realizadas a partir do gráfico de dispersão. Correlação elevada (~1) indica relação fortemente linear. Embora a correlação seja uma medida útil da direção e força da associação linear entre duas variáveis, não podemos utilizá-la para realizar, por exemplo, previsão. Além disto, a correlação mede apenas a força da relação <em>linear</em> para <em>um par</em> de variáveis.</p>
<p>Podemos proceder com o ajuste de um modelo de regressão linear simples para este par de variáveis.</p>
</section>
<section id="parte-2-análise-de-regressão" class="level3">
<h3 class="anchored" data-anchor-id="parte-2-análise-de-regressão">PARTE 2: Análise de Regressão</h3>
<p><strong>Estimação (Ajuste do Modelo):</strong></p>
<p>Análise de regressão permite não apenas medir a força da relação entre uma variável dependente e variáveis explicativas, como também descreve matematicamente esta relação.</p>
<p>A fim de simplificar a análise, vamos criar uma nova base de dados, incluindo somente as variáveis que serão utilizadas na construção do modelo de regressão linear simples:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói nova base de dados para análise</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>auto_mpg_invhp <span class="ot">&lt;-</span> auto <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># cria nova variável `inv_hp`</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">inv_hp  =</span> <span class="dv">1</span><span class="sc">/</span>hp) <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># seleciona apenas variáveis de interesse</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mpg, inv_hp)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># gera resumo dos novos dados  </span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(auto_mpg_invhp)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      mpg            inv_hp        
 Min.   : 9.00   Min.   :0.004348  
 1st Qu.:17.00   1st Qu.:0.007938  
 Median :22.75   Median :0.010695  
 Mean   :23.45   Mean   :0.010761  
 3rd Qu.:29.00   3rd Qu.:0.013333  
 Max.   :46.60   Max.   :0.021739  </code></pre>
</div>
</div>
<p>Note que o escopo do modelo não inclui <code>inv_hp</code> = 0. Portanto, já sabemos que o coeficiente linear da reta a ser estimada não terá significado prático.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói modelo de regressao linear simples (rls)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>auto_rls <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> inv_hp, <span class="at">data =</span> auto_mpg_invhp)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># variável de resposta: `mpg` </span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># variável explicativa: `inv_hp`</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># retorna coeficientes estimados do modelo de rls</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>auto_rls</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ inv_hp, data = auto_mpg_invhp)

Coefficients:
(Intercept)       inv_hp  
      3.936     1812.990  </code></pre>
</div>
</div>
<p>Veja nos resultados a forma da função de regressão (neste caso um modelo de 1a. ordem) e os valores estimados para os coeficientes da regressão. Aqui, a variável de resposta é <code>mpg</code> e a variável explicativa é <code>inv_hp</code>. Neste modelo não admitimos termos de ordem superior.</p>
<p><strong>Interpretação do Modelo Ajustado:</strong></p>
<p>Modelo Ajustado:</p>
<p><code>mpg = 3.936 + 1812.99 inv_hp</code> (eq. reta)</p>
<p>O coeficiente linear não tem significado prático, pois o escopo do modelo não inclui <code>inv-hp = 0</code>. Portanto, serve apenas de constante de ajuste para o modelo de regressão. O coeficiente angular representa o aumento esperado no rendimento do automóvel para um aumento unitário no inverso da potência do motor.</p>
<p>A função de regressão estimada indica que, para um acréscimo unitário no inverso da potência, o rendimento aumenta cerca de 1813 mpg, em média.</p>
<p><strong>Inferências:</strong></p>
<p>A figura abaixo mostra os dados disponíveis e a reta de regressão ajustada:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gera gráfico de dispersão</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto_mpg_invhp, <span class="fu">aes</span>(<span class="at">x =</span> inv_hp, <span class="at">y =</span> mpg)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># adiciona reta de regressão estimada</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GED16_AULA02_Exemplo_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Parece existir relação estatística linear entre <code>mpg</code> e <code>inv_hp</code>? O modelo parece capturar bem a relação entre as variáveis <code>mpg</code> e <code>inv_hp</code>? É útil utilizar a variável <code>inv_hp</code> para explicar a variação em <code>mpg</code>?</p>
<p>Essas perguntas podem ser respondidas através de inferências. Para isso, precisamos de mais informações a respeito do modelo ajustado.</p>
<p>Por hora, vamos assumir que o modelo é adequado aos dados, isto é, que satisfaz as hipóteses utilizadas para a construção do modelo de regressão. Satisfeitas as hipóteses do modelo, é possível proceder com inferências utilizando o modelo ajustado.</p>
<ol type="1">
<li>Resumo da Regressão</li>
</ol>
<p>Inicialmente, vamos analisar o resumo do modelo de regressão ajustado:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumo do modelo ajustado</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(auto_rls)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ inv_hp, data = auto_mpg_invhp)

Residuals:
    Min      1Q  Median      3Q     Max 
-17.348  -2.782  -0.106   2.438  15.030 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    3.9355     0.7341   5.361 1.42e-07 ***
inv_hp      1812.9900    64.8509  27.956  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.509 on 390 degrees of freedom
Multiple R-squared:  0.6671,    Adjusted R-squared:  0.6663 
F-statistic: 781.6 on 1 and 390 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Temos:</p>
<ul>
<li>um resumo da distribuição dos resíduos</li>
<li>estimativas para os coeficientes e respectivos desvios-padrão</li>
<li>valor da estatística-t e valor-p do teste bi-caudal para os coeficientes</li>
<li>estimativa para o desvio-padrão dos erros</li>
<li>resultados do teste-F (ANOVA)</li>
<li>coeficiente de determinação</li>
</ul>
<p>Os resíduos parecem ter distribuição simétrica com centro próximo de zero (valores absolutos de mínimo e máximo, 1Q e 3Q, na mesma ordem de grandeza e mediana próxima de zero). O coeficiente linear é estatisticamente diferente de zero, embora não nos interesse muito, pois o escopo do modelo não inclui <code>inv_hp</code> = 0. O coeficiente angular da regressão também é estatisticamente diferente de zero (veja o valor-p próximo de zero). Isto significa que existe uma associação estatisticamente linear entre <code>mpg</code> e <code>inv_hp</code>. A mesma conclusão pode ser obtida observando o valor-p associado à estatística-F para o modelo de regressão.</p>
<p>O coeficiente de determinação (<code>Multiple R-squared</code>) tem valor 0.6671. Isso significa que ao incluir a variável <code>inv_hp</code>, a variação total de <code>mpg</code> reduz em 66,71%, ou seja, a variável <code>inv_hp</code> consegue explicar cerca de 66,71% de toda a variabilidade obsevada em <code>mpg</code>. Se quisermos ser capazes de explicar um percentual maior da variabilidade da variável de resposta, talvez seja interessante incluir outras variáveis explicativas no modelo. O coeficiente de determinação ajustado (<code>Adjusted R2</code>) será explicado futuramente.</p>
<p>Alternativamente, podemos realizar inferência a respeito da utilidade da reta de regressão, isto é, da significância do coeficiente angular, utilizando a abordagem do teste-F (ANOVA).</p>
<ol start="2" type="1">
<li>ANOVA</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(auto_rls)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: mpg
           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
inv_hp      1 15889.9 15889.9  781.55 &lt; 2.2e-16 ***
Residuals 390  7929.1    20.3                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A tabela ANOVA dá os valores de SSR, SSE, MSR, MSE, os números de graus de liberdade associados a cada soma de quadrados, além do valor observado para a estatística F = MSR/MSE, e o valor-p correspondente. Note que, como não poderia ser diferente, o valor da estatística-F da tabela ANOVA é o mesmo apresentado no resumo da regressão, bem como os números de graus de liberdade e o valor-p.</p>
<ol start="3" type="1">
<li>Inferências sobre os parâmetros da regressão: IC’s para <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span>.</li>
</ol>
<p>Para nível de confiança 95%, temos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># IC para os coeficientes</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.lm</span>(auto_rls, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %      97.5 %
(Intercept)    2.492211    5.378823
inv_hp      1685.488783 1940.491127</code></pre>
</div>
</div>
<p>Concluímos com confiança de 95% que <span class="math inline">\(\beta_1\)</span> encontra-se no intervalo (1685.5, 1940.5), ou seja, com 95% de confiança, acreditamos que o rendimento do motor (em mpg) aumenta entre 1685.5 e 1940.5 para cada acréscimo unitário no inverso da potência. O coeficiente angular é positivo, o que confirma a expectativa de que o rendimento do motor deve aumentar com o aumento do inverso da potência, já que automóveis com maior potência costumam apresentar maior consumo de combustível.</p>
<p>Neste caso, não estamos interessados em inferências a respeito de <span class="math inline">\(\beta_0\)</span>; de toda forma, o coeficiente linear é estatisticamente significativo.</p>
<p>Note que o escopo do modelo de regressão está restrito à faixa de valores da variável explicativa utilizada na calibração do modelo. Neste exemplo, o modelo de regressão é significativo para valores de <code>inv_hp</code> na faixa aproximada de 4.3e-03 a 2.2e-02. Assim, pode não ser adequado utilizar o mesmo modelo para valores de <code>inv_hp</code> fora da faixa especificada, pois não temos garantia de que a relação linear encontrada se mantenha fora da região observada. Esta é uma consideração importante ao utilizar estimativas para coeficiente angular para realizar inferências a respeito da relação entre um par de variáveis, X e Y.</p>
<ol start="4" type="1">
<li>Inferências sobre a resposta esperada (média) <span class="math inline">\(\hat{Y}\)</span></li>
</ol>
<p>Se não tivéssemos o modelo de regressão, poderíamos realizar inferência a respeito da resposta esperada <code>mpg</code> construindo um intervalo de confiança para a média:</p>
<p><span class="math display">\[IC^{\mu_Y}_{(1-\alpha)100\%}: \quad \bar{y_n} \pm t_{\alpha/2, n-1} \times \frac{s_n}{\sqrt{n}},\]</span></p>
<p>onde:</p>
<p><span class="math inline">\(\bar{y}_n\)</span>: média da amostra de tamanho <span class="math inline">\(n\)</span><br>
<span class="math inline">\(s_n^2\)</span>: variação da amostra de tamanho <span class="math inline">\(n\)</span><br>
<span class="math inline">\(t_{\alpha/2, n-1}\)</span>: quantil a distribuição t-Student com <span class="math inline">\(n-1\)</span> graus de liberdade</p>
<p>Para realizar inferência com base na distribuição-t, a população deve ser normalmente distribuída:</p>
<div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a distribuição de `mpg` é normal?</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># inspeção visual (gráfico de quantis)</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(auto<span class="sc">$</span>mpg)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(auto<span class="sc">$</span>mpg)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># histograma</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(auto, <span class="fu">aes</span>(<span class="at">x =</span> mpg)) <span class="sc">+</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">binwidth =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># teste de normalidade de Shapiro-Wilk</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Ho: a distribuição é normal</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Ha: a distribuição não é normal</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(auto<span class="sc">$</span>mpg)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="GED16_AULA02_Exemplo_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="GED16_AULA02_Exemplo_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<pre><code>
    Shapiro-Wilk normality test

data:  auto$mpg
W = 0.96717, p-value = 1.049e-07</code></pre>
</div>
</div>
</div>
</div>
<p>O gráfico de probabilidades (quantis) e o resultado do <a href="https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test">teste de normalidade Shapiro-Wilk</a>, indicam que a distribuição de <code>mpg</code> não é normal. No entanto, geralmente testes de normalidade costumam ser bastante sensíveis para amostras grandes, de forma que mesmo pequenos desvios (sem significância prática) da normalidade podem levar à rejeição da hipótese nula. Mesmo no caso de distribuição não-normal, o TLC garante que, para amostras grandes, a média amostral tem distribuição aproximadamente normal. Portanto, podemos construir um intervalo de confiança para o rendimento médio da seguinte forma:</p>
<p><span class="math display">\[IC^{\mu_Y}_{(1-\alpha)100\%}: \quad \bar{y_n} \pm z_{\alpha/2} \times \frac{s_n}{\sqrt{n}},\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dados amostrais</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>n_aa <span class="ot">&lt;-</span> <span class="fu">length</span>(auto<span class="sc">$</span>mpg) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>sn   <span class="ot">&lt;-</span> <span class="fu">sd</span>(auto<span class="sc">$</span>mpg)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># nível de confiança</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>nc <span class="ot">&lt;-</span> <span class="fl">0.95</span>; alfa <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span>nc</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co"># estimativa pontual para rendimento médio</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(auto<span class="sc">$</span>mpg)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co"># margem de erro</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>margem_erro <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alfa)  <span class="sc">*</span> sn<span class="sc">/</span><span class="fu">sqrt</span>(n_aa)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="co"># limites do intervalo de confiança</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>lim_inf <span class="ot">&lt;-</span> ybar <span class="sc">-</span> margem_erro</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>lim_sup <span class="ot">&lt;-</span> ybar <span class="sc">+</span> margem_erro</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Assim, sem nenhuma informação adicional (além dos valores observados para a variável <code>mpg</code>) temos 95% de certeza de que o rendimento médio dos automóveis encontra-se no intervalo [24.09, 22.8].</p>
<p>Considerando o modelo de regressão ajustado, podemos realizar inferência a respeito da resposta esperada correspondente a um determinado valor da variável explicativa. Assim, suponha que se deseje estimar o rendimento médio de motores de automóveis com potência de 100 cavalos. Podemos construir um intervalo de confiança para o rendimento esperado de automóveis com essa potência:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># novo valor da variável explicativa</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>Xh <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">inv_hp =</span> <span class="fl">0.01</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># intervalo de confiança para resposta esperada</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>ic <span class="ot">&lt;-</span> <span class="fu">predict.lm</span>(auto_rls, <span class="at">newdata =</span> Xh, </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">interval=</span><span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O valor ajustado corresponde a 22.07; esta é a estimativa pontual e corresponde à resposta do modelo para <code>inv_hp = 0.01</code>. O intervalo de confiança 95% para a resposta média é (21.6, 22.5). O intervalo de confiança fornece uma faixa de valores plausíveis para o rendimento médio de automóveis com 100 hp de potência para o nível de confiança de 95%. Assim, é possível concluir com 95% de confiança que o rendimento esperado para automóveis com 100 hp de potência deve estar entre 22.1 e 22.5 mpg. Perceba que o intervalo de confiança para a resposta esperada obtido utilizando o modelo de regressão é muito mais preciso (tem menor largura) que aquele construído sem o modelo de regressão (com base apenas nos valores observados de <code>mpg</code>). Isso mostra que a inclusão da variável <code>inv_hp</code> ajuda a reduzir a incerteza a respeito da variável de interesse (<code>mpg</code>).</p>
<ol start="3" type="1">
<li>Previsão da resposta para uma nova observação</li>
</ol>
<p>Suponha que desejamos prever o rendimento de um novo automóvel cujo motor tem 100 hp de potência. Esta não é uma inferência a respeito da resposta esperada, ou seja, do rendimento médio de todos os automóveis com potência 100 hp. Queremos fazer a previsão de uma única realização da variável aleatória <code>mpg</code>, correspondente a um dado valor da variável explicativa <code>inv_hp</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># novo valor da variável explicativa</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>Xo <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">inv_hp =</span> <span class="fl">0.01</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># intervalo de confiança</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>ip <span class="ot">&lt;-</span> <span class="fu">predict.lm</span>(auto_rls, <span class="at">newdata =</span> Xo, </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note que o valor da estimativa pontual permanece o mesmo. Ele corresponde ao valor de resposta previsto pelo modelo de regressão. O intervalo de previsão para a nova observação correspondente a uma potência de 100 hp é dado por [13.2, 30.9]. O intervalo de previsão nos permite concluir com 95% de certeza que uma faixa plausível de valores de rendimento para o próximo automóvel que tiver potência de 100 hp está entre 13.2 e 30.9 mpg.</p>
<p>Note que o intervalo de previsão para o rendimento de um novo automóvel é mais largo que o intervalo de confiança para o rendimento médio dos automóveis que apresentam a potência especificada de 100hp.</p>
<p>No próximo capítulo, veremos como proceder para verificar a adequação do modelo aos dados disponíveis, isto é, como realizar o diagnóstico e como aplicar algumas medidas corretivas em caso de problemas.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>